image: ruby:2.5.3
services:
  - redis:latest
  - postgres:latest
variables:
  POSTGRES_DB: app_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

test:
  variables:
    RAILS_ENV: test
  script:
    - curl -sL https://deb.nodesource.com/setup_10.x | bash -
    - apt-get install -y nodejs
    - npm install -g yarn
    - yarn install
    - yarn test --ci
    - bundle install --path /cache
    - cp config/database.example.yml config/database.yml
    - cp config/secrets.example.yml config/secrets.yml
    - cp config/local_env.example.yml config/local_env.yml
    - bundle exec rake db:drop db:create db:schema:load
    - bundle exec rails webpacker:binstubs
    - bundle exec rake assets:precompile
    - bundle exec rake ci:build:commit
  tags:
    - tester-233

# TODO uncomment when deploy needed

# staging:
#   type: deploy
#   script:
#   - gem install rake
#   - gem install capistrano
#   - gem install capistrano-rvm
#   - gem install capistrano-rails
#   - gem install capistrano-rake
#   - gem install capistrano-bundler
#   - gem install capistrano3-puma
#   - gem install whenever
#   - cap staging deploy
#   tags:
#   - deployer
#   only:
#   - master
