default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: app_dev

test:
  <<: *default
  username: postgres
  host: postgres
  password: postgres
  database: app_test
